# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "docDock"
license = "MIT"
licenselink = "https://github.com/YanzhaoWu/hugo-theme-docdock/blob/master/LICENSE.md"
description = "GTDLBench"
homepage = "https://github.com/YanzhaoWu/hugo-theme-docdock"
repo = "https://github.com/YanzhaoWu/hugo-theme-docdock"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = 0.32

[author]
  name = "Yanzhao Wu"
  homepage = "http://yanzhaowu.me/"

[original]
  name = "Learn"
  homepage = "https://matcornic.github.io/hugo-learn-doc/basics/what-is-this-hugo-theme/"
  repo = "https://github.com/matcornic/hugo-theme-learn"
  licenselink = "https://github.com/matcornic/hugo-theme-learn/blob/master/LICENSE.md"
